export const jobListings = [
  {
    id: 1,
    title: "Garage Door Technician",
    slug: "garage-door-technician",
    department: "installation",
    type: "Full-time",
    location: "Houston, TX",
    experienceLevel: "mid",
    isRemote: false,
    postedDate: "2 days ago",
    description: "We're looking for skilled garage door technicians to join our fast-growing team! You'll be responsible for installing, repairing, and maintaining garage doors and openers for residential and commercial clients. Must have experience in garage door installation & repair, strong work ethic & problem-solving skills, and a customer-focused attitude.",
    responsibilities: ["Install, repair, and maintain residential and commercial garage doors and openers", "Diagnose and troubleshoot issues with garage door systems", "Provide excellent customer service and explain technical issues to clients", "Maintain accurate records of work performed and parts used", "Ensure all safety protocols are followed during installations and repairs", "Ensure all safety protocols are followed during installations and repairs", "Maintain company vehicles and equipment in good working condition", "Respond to emergency service calls as needed"],
    requirements: ["2+ years of experience in garage door installation and repair", "Knowledge of various garage door brands and opener systems", "Valid driver's license with clean driving record", "Strong mechanical aptitude and problem-solving skills", "Excellent customer service skills", "Ability to lift up to 50 pounds and work in various weather conditions", "High school diploma or equivalent"],
    preferredQualifications: ["Technical certification in a related field", "Experience with commercial garage door systems", "Knowledge of electrical systems and troubleshooting"],
    benefits: ["Competitive pay based on experience", "Health, dental, and vision insurance", "401(k) retirement plan with company match", "Paid time off and holidays", "Company vehicle and tools provided", "Ongoing training and career advancement opportunities", "Employee referral program"],
    salaryRange: "$45,000 - $65,000 annually, depending on experience",
  },
  {
    id: 2,
    title: "Senior Garage Door Installer",
    slug: "senior-garage-door-installer",
    department: "installation",
    type: "Full-time",
    location: "Dallas, TX",
    experienceLevel: "senior",
    isRemote: false,
    postedDate: "1 week ago",
    description: "Lead a team of installers and oversee complex garage door installations for commercial and high-end residential properties. The ideal candidate has 5+ years of experience in garage door installation, leadership skills, and the ability to train and mentor junior technicians.",
    responsibilities: ["Lead and supervise a team of garage door installers", "Oversee complex installations for commercial and high-end residential clients", "Train and mentor junior technicians", "Ensure all installations meet quality standards and building codes", "Coordinate with project managers and clients on installation schedules", "Troubleshoot and resolve complex technical issues", "Maintain inventory of parts and materials"],
    requirements: ["5+ years of experience in garage door installation", "Proven leadership experience", "In-depth knowledge of various garage door systems and openers", "Strong problem-solving and decision-making skills", "Excellent communication and customer service abilities", "Valid driver's license with clean driving record", "Ability to read and interpret blueprints and technical specifications"],
    preferredQualifications: ["Technical certification in a related field", "Experience with automated gate systems", "Knowledge of building codes and regulations", "Experience with project management software"],
    benefits: ["Competitive salary with performance bonuses", "Comprehensive health, dental, and vision insurance", "401(k) retirement plan with generous company match", "Paid time off and holidays", "Company vehicle and tools provided", "Leadership development training", "Career advancement opportunities"],
    salaryRange: "$65,000 - $85,000 annually, plus performance bonuses",
  },
  {
    id: 3,
    title: "Customer Service Representative",
    slug: "customer-service-representative",
    department: "customer-service",
    type: "Full-time",
    location: "Remote",
    experienceLevel: "entry",
    isRemote: true,
    postedDate: "3 days ago",
    description: "Join our customer service team to handle incoming calls, schedule appointments, and provide exceptional service to our clients. You'll be the first point of contact for customers and play a crucial role in ensuring their satisfaction.",
    responsibilities: ["Answer incoming calls and respond to customer inquiries", "Schedule service appointments and coordinate with technicians", "Process orders and provide product information", "Handle customer complaints and escalate issues when necessary", "Maintain accurate customer records in our CRM system", "Follow up with customers after service to ensure satisfaction", "Assist with administrative tasks as needed"],
    requirements: ["High school diploma or equivalent", "1+ years of customer service experience", "Excellent communication and interpersonal skills", "Proficiency with computers and ability to learn new software", "Strong problem-solving abilities", "Ability to multitask in a fast-paced environment", "Reliable internet connection for remote work"],
    benefits: ["Competitive hourly wage", "Health insurance options", "Paid training", "Flexible scheduling", "Performance bonuses", "Career advancement opportunities", "Employee discount program"],
    salaryRange: "$35,000 - $45,000 annually",
  },
  {
    id: 4,
    title: "Garage Door Repair Specialist",
    slug: "garage-door-repair-specialist",
    department: "repair",
    type: "Full-time",
    location: "Austin, TX",
    experienceLevel: "mid",
    isRemote: false,
    postedDate: "5 days ago",
    description: "Diagnose and repair garage door systems, including springs, cables, tracks, and openers. Must have experience with various garage door brands and models, troubleshooting skills, and the ability to explain technical issues to customers.",
    responsibilities: ["Diagnose and repair issues with residential and commercial garage door systems", "Replace broken springs, cables, rollers, and other components", "Repair and program garage door openers", "Perform preventive maintenance services", "Provide cost estimates for repairs", "Educate customers on proper garage door maintenance", "Maintain service records and inventory"],
    requirements: ["3+ years of experience in garage door repair", "Knowledge of various garage door brands and opener systems", "Strong troubleshooting and problem-solving skills", "Valid driver's license with clean driving record", "Excellent customer service and communication abilities", "Ability to work independently and manage time effectively", "Physical ability to lift heavy components and work in various positions"],
    preferredQualifications: ["Experience with commercial door systems", "Electrical troubleshooting skills", "Knowledge of smart home integration with garage door systems"],
    benefits: ["Competitive pay with commission opportunities", "Health, dental, and vision insurance", "401(k) retirement plan", "Paid time off and holidays", "Company vehicle and tools provided", "Ongoing technical training", "Career advancement opportunities"],
    salaryRange: "$50,000 - $70,000 annually, including commission",
  },
  {
    id: 5,
    title: "Sales Consultant",
    slug: "sales-consultant",
    department: "sales",
    type: "Full-time",
    location: "Houston, TX",
    experienceLevel: "mid",
    isRemote: false,
    postedDate: "1 week ago",
    description: "Generate leads and close sales for our garage door products and services. You'll meet with potential customers, assess their needs, provide quotes, and guide them through the selection process. Commission-based compensation with high earning potential.",
    responsibilities: ["Meet with potential customers to assess their garage door needs", "Provide product demonstrations and explain features and benefits", "Prepare and present quotes and proposals", "Follow up with prospects and close sales", "Maintain customer relationships and identify upselling opportunities", "Stay current on product knowledge and industry trends", "Attend trade shows and community events to generate leads"],
    requirements: ["2+ years of sales experience, preferably in home improvement", "Strong communication and negotiation skills", "Self-motivated with a drive to meet and exceed sales targets", "Valid driver's license with clean driving record", "Proficiency with CRM software and Microsoft Office", "Ability to work evenings and weekends as needed", "High school diploma or equivalent (Bachelor's degree preferred)"],
    preferredQualifications: ["Experience in the garage door or home improvement industry", "Knowledge of construction and building materials", "Background in consultative selling"],
    benefits: ["Competitive base salary plus uncapped commission", "Health, dental, and vision insurance", "401(k) retirement plan", "Paid time off and holidays", "Company vehicle or car allowance", "Sales training and professional development", "Performance bonuses and incentive trips"],
    salaryRange: "$60,000 - $100,000+ annually (including commission)",
  },
  {
    id: 6,
    title: "Apprentice Garage Door Technician",
    slug: "apprentice-garage-door-technician",
    department: "installation",
    type: "Full-time",
    location: "Dallas, TX",
    experienceLevel: "entry",
    isRemote: false,
    postedDate: "2 weeks ago",
    description: "Learn the garage door trade from experienced professionals. No prior experience required, but mechanical aptitude and willingness to learn are essential. We provide comprehensive training and a clear path for advancement.",
    responsibilities: ["Assist senior technicians with garage door installations and repairs", "Learn proper installation techniques and safety procedures", "Help with loading and unloading equipment and materials", "Maintain tools and equipment in good working condition", "Study garage door systems, components, and troubleshooting methods", "Participate in training sessions and skills development", "Provide support to the installation and repair teams"],
    requirements: ["Mechanical aptitude and interest in learning a skilled trade", "Strong work ethic and attention to detail", "Valid driver's license with clean driving record", "Ability to lift up to 50 pounds and work in various positions", "Good communication skills", "Reliable transportation to report to job sites", "High school diploma or equivalent"],
    benefits: ["Paid training program", "Competitive starting wage with scheduled increases", "Health insurance options", "401(k) eligibility after qualification period", "Paid time off accrual", "Tools provided", "Clear path for advancement to technician positions"],
    salaryRange: "$30,000 - $40,000 annually to start, with increase potential",
  },
  {
    id: 7,
    title: "Service Manager",
    slug: "service-manager",
    department: "repair",
    type: "Full-time",
    location: "Austin, TX",
    experienceLevel: "senior",
    isRemote: false,
    postedDate: "3 weeks ago",
    description: "Oversee our service department, manage technician schedules, and ensure quality workmanship and customer satisfaction. The ideal candidate has experience in the garage door industry, leadership skills, and a strong focus on operational efficiency.",
    responsibilities: ["Manage and coordinate the daily operations of the service department", "Schedule and dispatch technicians efficiently", "Monitor job quality and ensure customer satisfaction", "Handle escalated customer issues and complaints", "Manage inventory and order parts as needed", "Train and develop service technicians", "Track department metrics and implement improvements", "Ensure compliance with safety regulations and company policies"],
    requirements: ["5+ years of experience in the garage door industry", "3+ years of management experience", "Strong leadership and team-building skills", "Excellent customer service and problem-solving abilities", "Proficiency with scheduling software and Microsoft Office", "Knowledge of garage door systems and repair techniques", "Bachelor's degree in business or related field preferred"],
    preferredQualifications: ["Experience with service management software", "Background in process improvement", "Knowledge of inventory management systems", "Experience with budget management"],
    benefits: ["Competitive salary with performance bonuses", "Comprehensive health, dental, and vision insurance", "401(k) retirement plan with company match", "Paid time off and holidays", "Company vehicle or car allowance", "Leadership development training", "Profit sharing opportunities"],
    salaryRange: "$70,000 - $90,000 annually, plus bonuses",
  },
  {
    id: 8,
    title: "Marketing Specialist",
    slug: "marketing-specialist",
    department: "sales",
    type: "Full-time",
    location: "Remote",
    experienceLevel: "mid",
    isRemote: true,
    postedDate: "4 days ago",
    description: "Develop and implement marketing strategies to increase brand awareness and generate leads. You'll manage our social media presence, create content, coordinate advertising campaigns, and analyze marketing performance.",
    responsibilities: ["Develop and execute marketing campaigns across multiple channels", "Manage company social media accounts and create engaging content", "Write and edit website content, blog posts, and email newsletters", "Coordinate with external agencies on advertising initiatives", "Track and analyze marketing metrics to optimize performance", "Assist with event planning and trade show coordination", "Collaborate with sales team to develop lead generation strategies"],
    requirements: ["3+ years of marketing experience", "Strong writing and content creation skills", "Experience with social media management and digital marketing", "Proficiency with marketing analytics tools", "Knowledge of SEO and SEM principles", "Excellent organizational and project management abilities", "Bachelor's degree in Marketing, Communications, or related field"],
    preferredQualifications: ["Experience in the home improvement or service industry", "Graphic design skills and experience with Adobe Creative Suite", "Knowledge of CRM systems and marketing automation tools", "Experience with video production and editing"],
    benefits: ["Competitive salary", "Health, dental, and vision insurance", "401(k) retirement plan", "Paid time off and holidays", "Flexible remote work schedule", "Professional development opportunities", "Marketing conference attendance"],
    salaryRange: "$50,000 - $70,000 annually",
  },
];

export function getJobBySlug(slug) {
  return jobListings.find((job) => job.slug === slug);
}

export function getAllJobSlugs() {
  return jobListings.map((job) => job.slug);
}

export function getRelatedJobs(currentJobId, limit = 3) {
  const currentJob = jobListings.find((job) => job.id === currentJobId);

  if (!currentJob) return [];

  // Find jobs in the same department or with the same experience level
  return jobListings.filter((job) => job.id !== currentJobId && (job.department === currentJob.department || job.experienceLevel === currentJob.experienceLevel)).slice(0, limit);
}
